# Generated by Django 5.2.7 on 2025-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        help_text="Tipo de acción realizada (CREAR, MODIFICAR, ELIMINAR, etc.)",
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Nombre del modelo afectado",
                        max_length=50,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "objeto_id",
                    models.IntegerField(
                        help_text="ID del registro afectado",
                        verbose_name="ID del objeto",
                    ),
                ),
                (
                    "datos_anteriores",
                    models.JSONField(
                        blank=True,
                        help_text="Estado anterior del registro (para modificaciones)",
                        null=True,
                        verbose_name="Datos anteriores",
                    ),
                ),
                (
                    "datos_nuevos",
                    models.JSONField(
                        blank=True,
                        help_text="Nuevo estado del registro",
                        null=True,
                        verbose_name="Datos nuevos",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        help_text="IP desde la que se realizó la acción",
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de auditoría",
                "verbose_name_plural": "Logs de auditoría",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Respaldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="respaldos/%Y/%m/", verbose_name="Archivo de respaldo"
                    ),
                ),
                (
                    "fecha_respaldo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del respaldo"
                    ),
                ),
                (
                    "tamano_bytes",
                    models.BigIntegerField(verbose_name="Tamaño en bytes"),
                ),
                (
                    "exitoso",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el respaldo se completó exitosamente",
                        verbose_name="Exitoso",
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el respaldo falló",
                        verbose_name="Mensaje de error",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respaldo",
                "verbose_name_plural": "Respaldos",
                "ordering": ["-fecha_respaldo"],
            },
        ),
    ]
