# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs_auditoria",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["usuario", "fecha"], name="administrac_usuario_f519c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["modelo", "objeto_id"], name="administrac_modelo_56218c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(fields=["accion"], name="administrac_accion_6deaf6_idx"),
        ),
    ]
