# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONFIRMACION", "Confirmación"),
                            ("RECORDATORIO", "Recordatorio"),
                            ("CANCELACION", "Cancelación"),
                            ("RESULTADO", "Resultado disponible"),
                            ("SISTEMA", "Notificación del sistema"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        help_text="Título o asunto de la notificación",
                        max_length=200,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido de la notificación", verbose_name="Mensaje"
                    ),
                ),
                (
                    "leida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la notificación ha sido leída",
                        verbose_name="Leída",
                    ),
                ),
                (
                    "canal_enviado",
                    models.CharField(
                        help_text='Canal por el cual se "envió" la notificación',
                        max_length=10,
                        verbose_name="Canal de envío",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "simulada",
                    models.BooleanField(
                        default=True,
                        help_text="Indica que es una notificación simulada (siempre True)",
                        verbose_name="Simulada",
                    ),
                ),
                (
                    "cita_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de cita relacionada"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal_preferido",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Correo electrónico"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="EMAIL",
                        help_text="Canal preferido para recibir notificaciones",
                        max_length=10,
                        verbose_name="Canal preferido",
                    ),
                ),
                (
                    "confirmaciones",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir confirmaciones de citas agendadas",
                        verbose_name="Confirmaciones",
                    ),
                ),
                (
                    "recordatorios",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir recordatorios de citas próximas",
                        verbose_name="Recordatorios",
                    ),
                ),
                (
                    "cancelaciones",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones de cancelaciones",
                        verbose_name="Cancelaciones",
                    ),
                ),
                (
                    "resultados",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones de resultados disponibles",
                        verbose_name="Resultados",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencia_notificacion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de notificación",
                "verbose_name_plural": "Preferencias de notificaciones",
            },
        ),
    ]
