# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("propietarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto del pago en pesos colombianos",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de pago",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado del pago",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia o comprobante",
                        max_length=100,
                        verbose_name="Referencia/Comprobante",
                    ),
                ),
                (
                    "ultimos_4_digitos",
                    models.CharField(
                        blank=True,
                        help_text="Últimos 4 dígitos de la tarjeta (solo si es pago con tarjeta)",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Debe contener exactamente 4 dígitos",
                                regex="^\\d{4}$",
                            )
                        ],
                        verbose_name="Últimos 4 dígitos",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del pago"
                    ),
                ),
                (
                    "simulado",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si es un pago simulado (siempre True en este sistema)",
                        verbose_name="Pago simulado",
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos",
                        to="citas.cita",
                        verbose_name="Cita asociada",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="propietarios.propietario",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que registró el pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        help_text="Número único y consecutivo de la factura",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de factura",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="facturas/%Y/%m/", verbose_name="Factura PDF"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="propietarios.propietario",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="pagos.pago",
                        verbose_name="Pago asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
