# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("propietarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la mascota (2-50 caracteres)",
                        max_length=50,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("PERRO", "Perro"),
                            ("GATO", "Gato"),
                            ("AVE", "Ave"),
                            ("ROEDOR", "Roedor"),
                            ("REPTIL", "Reptil"),
                            ("OTRO", "Otro"),
                        ],
                        help_text="Especie de la mascota",
                        max_length=10,
                        verbose_name="Especie",
                    ),
                ),
                (
                    "raza",
                    models.CharField(
                        help_text="Raza de la mascota",
                        max_length=50,
                        verbose_name="Raza",
                    ),
                ),
                (
                    "edad",
                    models.PositiveIntegerField(
                        help_text="Edad de la mascota en años",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Edad",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso de la mascota en kilogramos (opcional)",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Peso",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Macho"), ("H", "Hembra")],
                        help_text="Sexo de la mascota (opcional)",
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales (máx 300 caracteres)",
                        max_length=300,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de la mascota",
                        null=True,
                        upload_to="mascotas/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la mascota está activa (no transferida ni fallecida)",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        help_text="Propietario actual de la mascota",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mascotas",
                        to="propietarios.propietario",
                        verbose_name="Propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="TransferenciaMascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_transferencia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de transferencia"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Motivo de la transferencia (opcional)",
                        max_length=500,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        help_text="Mascota transferida",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "propietario_anterior",
                    models.ForeignKey(
                        help_text="Propietario que transfiere la mascota",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_salientes",
                        to="propietarios.propietario",
                        verbose_name="Propietario anterior",
                    ),
                ),
                (
                    "propietario_nuevo",
                    models.ForeignKey(
                        help_text="Propietario que recibe la mascota",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_entrantes",
                        to="propietarios.propietario",
                        verbose_name="Propietario nuevo",
                    ),
                ),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        help_text="Usuario que realizó la transferencia",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de mascota",
                "verbose_name_plural": "Transferencias de mascotas",
                "ordering": ["-fecha_transferencia"],
            },
        ),
        migrations.AddIndex(
            model_name="mascota",
            index=models.Index(
                fields=["propietario", "nombre"], name="mascotas_ma_propiet_8b7630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mascota",
            index=models.Index(
                fields=["especie"], name="mascotas_ma_especie_ace5ed_idx"
            ),
        ),
    ]
