# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("CONSULTA", "Consulta veterinaria"),
                            ("VACUNACION", "Vacunación"),
                            ("DESPARASITACION", "Desparasitación"),
                            ("CIRUGIA", "Cirugía"),
                            ("CONTROL_PESO", "Control de peso"),
                            ("PELUQUERIA", "Peluquería"),
                            ("VENTA_PRODUCTOS", "Venta de productos"),
                            ("OTRO", "Otro"),
                        ],
                        help_text="Tipo de servicio veterinario",
                        max_length=20,
                        unique=True,
                        verbose_name="Nombre del servicio",
                    ),
                ),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        help_text="Duración estimada del servicio (mínimo 15 minutos)",
                        validators=[django.core.validators.MinValueValidator(15)],
                        verbose_name="Duración en minutos",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del servicio en pesos colombianos",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del servicio (opcional)",
                        max_length=500,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el servicio está disponible para agendamiento",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "color_calendario",
                    models.CharField(
                        default="#00736A",
                        help_text="Color en formato hexadecimal para mostrar en calendario",
                        max_length=7,
                        verbose_name="Color en calendario",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["nombre"],
            },
        ),
    ]
