# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CITAS", "Reporte de citas"),
                            ("SERVICIOS", "Reporte de servicios"),
                            ("FINANCIERO", "Reporte financiero"),
                            ("PACIENTES", "Reporte de pacientes"),
                            ("VETERINARIOS", "Reporte de veterinarios"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de reporte",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del reporte generado",
                        max_length=200,
                        verbose_name="Nombre del reporte",
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        help_text="Parámetros utilizados para generar el reporte",
                        verbose_name="Parámetros",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel")],
                        max_length=10,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="reportes/%Y/%m/", verbose_name="Archivo del reporte"
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de generación"
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-fecha_generacion"],
            },
        ),
    ]
