# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mascotas", "0001_initial"),
        ("propietarios", "0001_initial"),
        ("servicios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[
                            (1, "Emergencias"),
                            (2, "Cirugías"),
                            (3, "Servicios médicos"),
                            (4, "Peluquería"),
                            (5, "Venta de productos"),
                        ],
                        help_text="Nivel de prioridad en la lista de espera",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Observaciones"
                    ),
                ),
                (
                    "atendido",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si ya se le asignó una cita",
                        verbose_name="Atendido",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        help_text="Mascota en lista de espera",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_espera",
                        to="mascotas.mascota",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        help_text="Servicio solicitado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.servicio",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de espera",
                "verbose_name_plural": "Listas de espera",
                "ordering": ["prioridad", "fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha de la cita", verbose_name="Fecha"
                    ),
                ),
                (
                    "hora",
                    models.TimeField(
                        help_text="Hora de inicio de la cita", verbose_name="Hora"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                            ("INASISTENCIA", "Inasistencia"),
                        ],
                        default="PROGRAMADA",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "es_emergencia",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es una cita de emergencia (sin restricciones de horario)",
                        verbose_name="Es emergencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones o motivo de la cita",
                        max_length=500,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(
                        blank=True,
                        help_text="Motivo por el cual se canceló la cita",
                        max_length=500,
                        verbose_name="Motivo de cancelación",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        help_text="Mascota a atender",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        help_text="Propietario de la mascota",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="propietarios.propietario",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        help_text="Servicio veterinario solicitado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="servicios.servicio",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        help_text="Usuario que creó la cita",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario creador",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        help_text="Veterinario asignado",
                        limit_choices_to={"rol": "VETERINARIO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veterinario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-fecha", "-hora"],
                "indexes": [
                    models.Index(
                        fields=["fecha", "hora"], name="citas_cita_fecha_46fbd6_idx"
                    ),
                    models.Index(
                        fields=["veterinario", "fecha"],
                        name="citas_cita_veterin_1c4296_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="citas_cita_estado_2000d2_idx"
                    ),
                ],
                "unique_together": {("veterinario", "fecha", "hora")},
            },
        ),
    ]
