# Generated by Django 5.2.7 on 2025-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="pagado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la cita ha sido pagada",
                verbose_name="Pagado",
            ),
        ),
    ]
