# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Propietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo del propietario (3-100 caracteres)",
                        max_length=100,
                        verbose_name="Nombre completo",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="Número de documento único del propietario",
                        max_length=20,
                        unique=True,
                        verbose_name="Documento de identidad",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="Teléfono de contacto (7-15 dígitos)",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El teléfono debe contener entre 7 y 15 dígitos numéricos",
                                regex="^\\d{7,15}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        help_text="Correo electrónico único del propietario",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                        help_text="Dirección de residencia (opcional, máx 200 caracteres)",
                        max_length=200,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el propietario está activo en el sistema",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuario del sistema asociado al propietario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propietario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietarios",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["documento"], name="propietario_documen_15cf92_idx"
                    ),
                    models.Index(
                        fields=["correo"], name="propietario_correo_6a4c7b_idx"
                    ),
                ],
            },
        ),
    ]
