# Generated by Django 5.2.7 on 2025-11-23 03:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("mascotas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoVacunacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        help_text="Número único del certificado",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de certificado",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="certificados/%Y/%m/", verbose_name="Certificado PDF"
                    ),
                ),
                (
                    "vacunas_incluidas",
                    models.TextField(
                        help_text="Lista de vacunas incluidas en el certificado",
                        verbose_name="Vacunas incluidas",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificados_vacunacion",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        limit_choices_to={"rol": "VETERINARIO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veterinario emisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de vacunación",
                "verbose_name_plural": "Certificados de vacunación",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="HistorialClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_consulta", models.DateField(verbose_name="Fecha de consulta")),
                (
                    "diagnostico",
                    models.TextField(
                        help_text="Diagnóstico realizado por el veterinario",
                        verbose_name="Diagnóstico",
                    ),
                ),
                (
                    "tratamiento",
                    models.TextField(
                        help_text="Tratamiento prescrito", verbose_name="Tratamiento"
                    ),
                ),
                (
                    "vacunas",
                    models.TextField(
                        blank=True,
                        help_text="Vacunas administradas durante la consulta",
                        verbose_name="Vacunas aplicadas",
                    ),
                ),
                (
                    "procedimientos",
                    models.TextField(
                        blank=True,
                        help_text="Procedimientos médicos realizados",
                        verbose_name="Procedimientos realizados",
                    ),
                ),
                (
                    "evolucion",
                    models.TextField(
                        help_text="Estado y evolución del paciente",
                        verbose_name="Evolución",
                    ),
                ),
                (
                    "peso_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso registrado durante la consulta",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Peso actual (kg)",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historiales",
                        to="citas.cita",
                        verbose_name="Cita asociada",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historiales",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        limit_choices_to={"rol": "VETERINARIO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historiales_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veterinario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial clínico",
                "verbose_name_plural": "Historiales clínicos",
                "ordering": ["-fecha_consulta"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Archivo adjunto (PDF, JPG, PNG - máx 10MB)",
                        upload_to="historiales/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=10, verbose_name="Tipo de archivo"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de carga"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que cargó el archivo",
                    ),
                ),
                (
                    "historial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="historiales.historialclinico",
                        verbose_name="Historial clínico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de historial",
                "verbose_name_plural": "Archivos de historiales",
                "ordering": ["-fecha_carga"],
            },
        ),
    ]
